CREATE TABLE `mytable` (
  `Nr` DOUBLE,
  `Jokes` VARCHAR(1024)
);

INSERT INTO `mytable` (`Nr`,`Jokes`)
VALUES
(1,'"Du hast aber schon mal einen Schornstein gemauert, oder?" "Nein, das ist ein Versuchskaminchen."'),
(2,'Aus welcher Stadt kommen die Audiokabel? Auxburg'),
(3,'Axl Rose hat seiner nordfriesischen Freundin ein Liebeslied geschrieben: Sweet Child of Moin.'),
(4,'Brennholzverleih.'),
(5,'Dem Reh fallen die Haare aus. Der Doktor weist es in eine Rehhaarklinik ein.'),
(6,'Der Brachiosaurus nutzt Windows, der Tyrannosaurus Macs.'),
(7,'Der Erfinder des Post-It-Zettels ist gestorben. Die tröstliche Nachricht: Es gibt ein Kleben nach dem Tod.'),
(8,'Der Fischer ist sauer! Wieso? Er hat kein Netz.'),
(9,'Der Pfannkuchenbäcker ist an seinem eigenen Teig erstickt. Einfach crepiert.'),
(10,'Egal wie "dicht" du bist, Goethe war Dichter.'),
(11,'Egal wie du kochst, Karl Marx.'),
(12,'Egal wie gut Du fährst, Züge fahren Güter.'),
(13,'Egal wie viel CD''s du hast. Karl hat Mercedes.'),
(14,'Eier sind gar nicht so ungefährlich. Eines hat immerhin den Sheriff erschossen!'),
(15,'Ein Besoffener beschimpft und beleidigt ein Helium. Und was macht es? Es reagiert nicht.'),
(16,'Ein Gockel bekommt eine Blasterpistole. Aus versehen bringt er damit alle Hühner um. Da ist der Hahn Solo.'),
(17,'Einbruch bei Adidas. Was schickt die Polizei? Drei Streifen.'),
(18,'Es gibt eine neue Band: die 1023 Megabyte. Sie hatten noch nie nen Gig.'),
(19,'Fliegt ein Kuckuck übers Meer. Grüßt ihn ein Hai: "Hi!" - "Kuckuck!"'),
(20,'Fragt der Polizist: Haben sie Restalkohol? - Nee, alles ausgetrunken.'),
(21,'Fragt der eine Dino den Anderen: "Warum siehst Du heute so zerknirscht aus?" "Ach", sagt der Andere, "ich bin heut etwas sedimental...".'),
(22,'Geben sich verliebte Anästhesisten eigentlich Narkosenamen?'),
(23,'Geht ein Cowboy zum Friseur. Als er wieder rauskommt ist sein Pony weg.'),
(24,'Geht eine schwangere Frau zum Bäcker und sagt: "Ich bekomme ein Brot."'),
(25,'Huch, meine Uhr ist runter gefallen. Ich kann sie nicht aufheben. - Ich hab kein Uhrheberrecht.'),
(26,'Hüpft ein Rudel Gurken durch den Wald. Was ist falsch? Gurken sind keine Rudeltiere.'),
(27,'Ich bin so unentschlossen. Als japanischer Krieger wäre ich ein Nunja.'),
(28,'"Ich brauche eine Krankschreibung." - "Was fehlt ihnen denn?" -  "Eine Krankschreibung."'),
(29,'Ich habe bei Spiderman angerufen, aber der hatte kein Netz.'),
(30,'Ich habe bei den Weight Watchers angerufen: Aber keine hat abgenommen.'),
(31,'Ich habe bei einem Brötchen angerufen, aber: War belegt.'),
(32,'Ich habe bei nem DJ angerufen: Der hat einfach aufgelegt.'),
(33,'Ich habe beim Arzt angerufen: Ich wurde aber nicht verbunden.'),
(34,'Ich habe beim Bäcker angerufen, da ging aber nur die Mehlbox ran.'),
(35,'Ich habe beim Metzger angerufen, aber kein Schwein ging ran.'),
(36,'Ich habe das Herz eines Löwen ... und lebenslanges Verbot im Leipziger Zoo.'),
(37,'Ich habe einem Hipster ans Schienbein getreten. Jetzt hopster.'),
(38,'Ich habe einen total lieben Hund, der ist so ruhig - der hat sogar den No-Bell preis gewonnen.'),
(39,'Ich habe in der Botschaft angerufen, aber keiner ging ran. War wohl Kanada.'),
(40,'Ich habe meiner Frau zu Weihnachten einen Nerz geschenkt und jetzt weigert sie sich, das Tier zu füttern.'),
(41,'Ich wollte einen Witz über die Deutsche Bahn machen, aber ich wusste nicht ob der ankommt.'),
(42,'Im Restaurant: Isst Du gerne wild? - Nein, ganz normal und langsam.'),
(43,'In Mittelamerika gibt es kaum gute Tapezierer - aber dafür Guatemala!'),
(44,'In welche Kirche geht der Regisseur? In die Cutholische.'),
(45,'In welchem Land ist man so langsam wie eine Schnecke? In Kriechenland.'),
(46,'Klaus war echt nervig, deshalb bekam er nie frische Brötchen. Klaus störte Bäcker.'),
(47,'Kommt ein Dachdecker in eine Bar. — Sagt der Wirt: "Der geht aufs Haus."'),
(48,'Kommt ein Frosch in den Milchladen. Fragt die Verkäuferin: "Was willst du denn?" - Sagt der Frosch: "Quak."'),
(49,'Kommt ein Igel in die Konditorei: "Einmal Rumkugeln bitte" -- Wenn sie wollen, wir haben gerade frisch gewischt.'),
(50,'Kommt ein Pferd in den Blumenladen: "Haben sie Mageriten?" (ma'' geritten)'),
(51,'Mein Arzt hat eine südamerikanische Augenkrankheit bei mir diagnostiziert - ich "Chile".'),
(52,'Mein Hund ein echter Charmeur. Immer wenn ich ihn fragt: Na wie sehe ich aus, sagt er: Wau!'),
(53,'Meine Gitarre ist zu leise um mittelalterliche Musik zu spielen. Ich brauch eine Laute.'),
(54,'Mir ist kalt - ich geh mal in die Ecke. Da sind 90 Grad.'),
(55,'Mit wem geht Peter Pan in die Bar? Trinker-Bell.'),
(56,'Neulich im Tatort: Wo waren Sie zur Tatzeit? - Im Internet!'),
(57,'Nordischer Gott der gewaltfreien Konfliktlösung? Der Mediathor.'),
(58,'"Papa, in Ägypten ist nächste Woche auch keine Schule!" -- "Ok?" -- "Ja, die haben da Sphinxferien!"'),
(59,'Piraten gönnen sich morgens am Liebsten ein Frühstücks-Aye.'),
(60,'Sagt der Pessimist: "Schlimmer geht nicht!" - Sagt der Optimist: "Doch!"'),
(61,'Sagt der Walfisch zum Tuhnfisch: "Was wollen wir tun, Fisch?" Sagt der Thunfisch: "Du hast die Wahl, Fisch!"'),
(62,'Sagt die Erbse zur anderen: Vorsicht, da ist eine Trepepepepepepepepe...'),
(63,'Sagt die eine Kerze zur anderen: Du, ist Wasser eigentlich gefährlich? - Sagt die andere: Davon kannst Du ausgehen.'),
(64,'Sagt die eine Sicherung zur anderen: Lass uns zusammen durchbrennen!'),
(65,'Sagt die eine Wand zur anderen Wand: Wir treffen uns an der Ecke.'),
(66,'Sie haben Meeresbiologie studiert? Als Walfach.'),
(67,'Sprechstundenhilfe: "Warum tragen Sie eine Augenklappe?" "Ich bin Piratpatient."'),
(68,'Steht ein Baum allein im Wald...'),
(69,'Steht ein Pils im Wald. Kommt ein Hase und trinkt es aus. Und warum steht ein Pils im Wald? Weil die Tannen zapfen.'),
(70,'Stiftung Warentest hat Besteck getestet. Das Messer hat am besten abgeschnitten.'),
(71,'Tage an denen man plant, Bananen zu essen, nennt man Bananenplantage.'),
(72,'Tonic ohne Alkohol ist übrigens ginlos.'),
(73,'Treffen sich zwei Jäger: Beide Tot.'),
(74,'Treffen sich zwei Magneten: "Was zieh ich heute bloß an?"'),
(75,'Unter welchen Krankheitssymptomen leiden Astronauten? Reizhouston.'),
(76,'Unterhalten sich zwei Fliesenleger: "Wo sind denn die ganzen Fliesen hin?" "Oh, die muss ich wohl verlegt haben."'),
(77,'Von welchem Dinosaurier bekommt Asterix seine Brille? Einem Archäopterix.'),
(78,'Wann gehen U-Boote unter? Am Tag der offenen Tür.'),
(79,'Warum darf das Neutron nicht in die Disco? Heute nur geladene Gäste!'),
(80,'Warum findet ein Henker nie den Rückweg? Weil der nur die Hinrichtung kennt.'),
(81,'Warum fliegen Störche im Winter in den Süden? - Weil Laufen zu lange dauern würde.'),
(82,'Warum gibt es in Booten keinen Honig? Weil es auf Schiffen ka-bienen gibt.'),
(83,'Warum haben Fische Schuppen? Damit sie ihre Fahrräder unterstellen können.'),
(84,'Warum haben diese Fische so ausgesprochen gute Zähne? Das sind Kariesprofilachse.'),
(85,'Warum ist der Florist über seine Lieferung traurig? Sie ist eingegangen.'),
(86,'Warum klaut Robin Hood Deo? Um es unter den Armen zu verteilen!'),
(87,'Warum können Dinos nachts so schlecht sehen? Weil sie dann schlafen.'),
(88,'Warum können Seeräuber schlecht mit Kreisen Rechnen? Weil sie Pi-Raten!'),
(89,'Warum können Skelette so schlecht lügen? Die sind so einfach zu durchschauen.'),
(90,'Warum leben Haie im Salzwasser? Weil sie von Pfefferwasser niesen müssen.'),
(91,'Warum muss die Spinne grillen? Sie ist ein Weberknecht.'),
(92,'Warum sind Fußballer eine Gefahr im Straßenverkehr? Weil sie bei rot gehen müssen.'),
(93,'Warum sind bei IKEA Pfeile am Boden? Weil es ein Einrichtungshaus ist.'),
(94,'Warum steht die Freiheitsstatue in New York? Weil sie sich nicht setzen kann.'),
(95,'Warum summen Bienen? Weil sie den Text nicht kennen.'),
(96,'Warum wachsen auf dem Mond keine Blumen? Zu wenig Erde.'),
(97,'Was bekommen Schuhe, wenn man sie in Salzwasser legt? Mehr Sole.'),
(98,'Was bekommt ein Kannibale, der zu spät zum Essen kommt? Die kalte Schulter.'),
(99,'Was benutzt ein Bär als Eingabegerät? Eine Tatzatur.'),
(100,'Was bestellt ein Maulwurf im Restaurant? — Ein Drei-Gänge-Menü.'),
(101,'Was braucht die verletzte Straße? Pflaster.'),
(102,'Was bringt uns in 30 Jahren mit zunehmendem Klimawandel Pakete? Postboote.'),
(103,'Was denken sich die Gletscher zum Klimawandel? Wir werden Seen.'),
(104,'Was eine Raupe in einer Rüstung? Ein Raupritter.'),
(105,'Was erhält man von Kühen in einem Erdbebengebiet? Milchshakes'),
(106,'Was erzählen sich holländische Süßspeisen am liebsten? Vla-chwitze.'),
(107,'Was erzählt Weizen sich gegenseitig beim Campen? Grieselgeschichten.'),
(108,'Was essen Alligatoren am liebsten? Krokoli.'),
(109,'Was essen Autos am liebsten? — Parkplätzchen.'),
(110,'Was essen Katzen am liebsten? Mausmannskost.'),
(111,'Was essen Piraten am liebsten zum Frühstück? Aye.'),
(112,'Was essen Piraten am liebsten? — Kapern.'),
(113,'Was essen Verliebte am liebsten? Kusskuss.'),
(114,'Was fliegt durchs All und ist gut für die Verdauung? Ein Pflaumschiff.'),
(115,'Was flitzt essbares über die Straßen? Eine Cartoffel.'),
(116,'Was fraß der Triceratops wenn er entspannen wollte? Ur-Laub.'),
(117,'Was freut sich und stinkt? - Das Gefurztagskind.'),
(118,'Was für ein Gefühl hatte Mozart beim Komponieren? Einen Haydn-Spaß.'),
(119,'Was gibt es bei Olympia— Teilnehmern zum Nachtisch? — Fackelpudding!'),
(120,'Was gräbt und ist aus der Puste? Eine Schnaufel.'),
(121,'Was hat Haare und wird gebraten? Bartkartoffeln.'),
(122,'Was hat acht Arme und fliegt durchs Weltall? Eine Krakete.'),
(123,'Was hat acht Beine und schummelt? Eine Mogelspinne.'),
(124,'Was hat ein Mann, der im Dreieck läuft? Kreislaufprobleme.'),
(125,'Was hat einen Beutel und schießt? Ein Penguruh.'),
(126,'Was hoppelt über die Wiese und raucht aus den Ohren? Ein Kaminchen.'),
(127,'Was hält warm und auch Ordnung? Der Pullizist'),
(128,'Was hört man wenn man sich einen Döner ans Ohr hält? Das Schweigen der Lämmer.'),
(129,'Was isst Familie Biber zu abend? Tischstäbchen.'),
(130,'Was isst der vegane Fuchs? Gänseblümchen.'),
(131,'Was ist braun und fährt im Winter die Hänge hinunter? Ein Snowbroad.'),
(132,'Was ist braun und hilft dir, wenn du traurig bist? Ein Trost-brot.'),
(133,'Was ist braun und hängt mit nem Warndreieck im Baum? Ein Pannenzapfen.'),
(134,'Was ist braun und schwimmt unter Wasser? Ein U-Brot.'),
(135,'Was ist braun, gesund und beleidigt? Schmollkornbrot.'),
(136,'Was ist braun, kann fliegen und macht Kindern die Zähne kaputt? - Die Toffi-Fee!'),
(137,'Was ist braun, lebt im Nil und schmeckt lecker? Ein Schokodil.'),
(138,'Was ist braun, lecker und gesund? Schogolade.'),
(139,'Was ist bunt und will dringend aus dem Zimmer raus? Ein Fluchtsalat.'),
(140,'Was ist bunt, leuchtet und kann nicht schwimmen? ein Bagger mit Lichterkette.'),
(141,'Was ist bunt, süß und ein bisschen einfach gestrickt? Ein Dummibärchen.'),
(142,'Was ist das Gegenteil vom Brillenfisch? Ein Sehstern.'),
(143,'Was ist das Gegenteil von Katalog? Kata sagt die Wahrheit.'),
(144,'Was ist das agressivste Milchprodukt? Schlagsahne.'),
(145,'Was ist das sauberste Tier der Savanne? Die Hygiäne.'),
(146,'Was ist das schnellste Fortbewegungsmittel der Maus? Der Busard.'),
(147,'Was ist das unartigste Insekt? Die Rebelle.'),
(148,'Was ist der schlauste Ast? Ein Gymniasast.'),
(149,'Was ist die größte Anerkennung unter Aquarellisten? "Verläuft bei Dir!"'),
(150,'Was ist ein Boxer? Schlagfertig.'),
(151,'Was ist ein Cowboy ohne Pferd? Ein Sattelschlepper.'),
(152,'Was ist ein Keks unter einem Baum? Ein schattiges Plätzchen.'),
(153,'Was ist ein Verkehrswende bewusster Ökosaurier? Ein Velo-ciraptor.'),
(154,'Was ist eine Glühbirne, die schockiert zu Boden fällt? Fassungslos!'),
(155,'Was ist eine Kastanie hinter Gittern? Eine Knastanie.'),
(156,'Was ist gefährlicher als Zigarettenrauchen? Gleise. Nur ein Zug und das war’s!'),
(157,'Was ist gelb und flattert im Wind? Eine Fahnane.'),
(158,'Was ist gelb und hüpft durch den Wald? Ein Postfrosch.'),
(159,'Was ist gelb und läuft den Baum hoch? Ein Posthörnchen.'),
(160,'Was ist gelb und schießt? Eine Banone.'),
(161,'Was ist gelb und schwimmt über''n See? Eine Schwanane.'),
(162,'Was ist gelb und steht am Fenster? - Eine Spannanas.'),
(163,'Was ist grau und sitzt auf dem Klo? Ein Kloala.'),
(164,'Was ist groß, braun und schreibt undeutlich? Ein Kritz-li-bär.'),
(165,'Was ist groß, grau und interessiert niemanden? Ein Irrelephant.'),
(166,'Was ist groß, grau und ruft gleich an? Ein Telefant.'),
(167,'Was ist grün und fliegt durchs Weltall? Ein Salatelit.'),
(168,'Was ist grün und fährt Pandabären zur Arbeit? Ein Bam-bus.'),
(169,'Was ist grün und fährt mit der Bahn? Eine Zughini'),
(170,'Was ist grün und gewinnt jedes Rennen? Ein Schnellerie.'),
(171,'Was ist grün und heiß? Eine Brennnessel.'),
(172,'Was ist grün und hüpft durch den Wald? Ein Rudel Gurken.'),
(173,'Was ist grün und liegt im Sarg? Eine Sterbse.'),
(174,'Was ist grün und macht die Toilette sauber? Ein Klokodil.'),
(175,'Was ist grün und schnarcht am Wegesrand? Eine Pennnessel.'),
(176,'Was ist grün und will dringend ins Zimmer? Ein Klopfsalat.'),
(177,'Was ist grün, blind und kann singen? Kiwi Wonder.'),
(178,'Was ist grün, hängt an der Türklinke und guckt durchs Schlüsselloch? Ein Spionat.'),
(179,'Was ist grün, sauer und versteckt sich vor der Polizei? Ein Essig-Schurke.'),
(180,'Was ist heiß und flauschig? Eine Fellkartoffel.'),
(181,'Was ist klein und schwarz und dreht sich auf der Wiese? Ein Maulwurf beim Hammerwerfen.'),
(182,'Was ist klein, glitschig und immer schlecht gelaunt? Eine Maulquappe.'),
(183,'Was ist klein, rot, rund und voller Magie? Cherry Potter.'),
(184,'Was ist langsam, wird steinalt und macht einen Riesenlärm? Eine Schildtröte.'),
(185,'Was ist lila und bedient im Restaurant? Eine Obergine.'),
(186,'Was ist lässig und hat einen Euter? Eine Kuhl.'),
(187,'Was ist niedlich, lebt in Australien und stinkt? Der Kloala.'),
(188,'Was ist orange und kann nicht still sitzen? Eine Zappelsine.'),
(189,'Was ist orange und läuft durch die Berge? Eine Wandarine.'),
(190,'Was ist pink und trägt ein Maschinengewehr? Ein Rambodieschen.'),
(191,'Was ist rosa und kennt sich gut mit Waffen aus? Die Ballerrina.'),
(192,'Was ist rot und fährt Fahrrad? Raddieschen.'),
(193,'Was ist rot und schlecht für die Zähne? Ein Ziegelstein.'),
(194,'Was ist rot und steht an der Straße? Eine Hagenutte.'),
(195,'Was ist rot und wiehert? Eine Pferdbeere.'),
(196,'Was ist rot, rund und sitzt auf dem Klo? Eine Klomate.'),
(197,'Was ist schwarz, rot und lebt in der Arktis? Ein Pinguin mit Sonnenbrand.'),
(198,'Was ist schwarz-weiß und 50 cm in der Luft? Ein Schwebra.'),
(199,'Was ist schwarz-weiß und explodiert? Ein Sprenguin.'),
(200,'Was ist schwarz-weiß und hüpft auf und ab? Ein Springuin.'),
(201,'Was ist schwarz-weiß und sitzt auf der Schaukel? Ein Schwinguin.'),
(202,'Was ist sehr schlecht für die Zähne? Bombbombs.'),
(203,'Was ist sehr schlecht für die Zähne? Kauwumm.'),
(204,'Was ist süß und schwingt sich von Torte zu Torte? Tarzipan.'),
(205,'Was ist süß, klebrig und geht durch die Wüste? Ein Karamel.'),
(206,'Was ist unter der Erde und stinkt? Eine Furzel.'),
(207,'Was ist unzufrieden, redet undeutlich und lebt im Wasser? Eine Mies-Nuschel.'),
(208,'Was ist weiß und fliegt durch den Wald? Biene Mayo.'),
(209,'Was ist weiß und läuft den Berg hoch? Ein Marschmellow.'),
(210,'Was ist weiß und rennt den Berg wieder hoch? Eine Lawine mit Heimweh.'),
(211,'Was ist weiß und schnarcht auf der Wiese? Ein Schlaf.'),
(212,'Was ist weiß und springt von Baum zu Baum? Ein Tierarzt bei der Zeckenimpfung.'),
(213,'Was ist weiß und steht hinter einem Baum? Eine scheue Milch.'),
(214,'Was ist weiß und stört beim Essen? Eine Lawine.'),
(215,'Was ist weiß und tanz im Wald ums Feuer? Rumpelpilzchen.'),
(216,'Was ist wohlhabend und springt von Ast zu Ast? Ein Scheichhörnchen.'),
(217,'Was ist, wenn man bei IKEA klaut? Man wird vermöbelt.'),
(218,'Was kauft ein Mann mit zwei linken Füßen im Schuhgeschäft? Flip Flips.'),
(219,'Was kommt aufs Brot und schmeckt nach Kleister? Kleberwurst.'),
(220,'Was lebt im Meer und spricht undeutlich? Die Nuschel.'),
(221,'Was lebt in der Savanne und ist immer sauber? Eine Hygiäne.'),
(222,'Was liegt am Strand und kann man nicht gut verstehen und ist auch noch erkältet? Eine Niesnuschel.'),
(223,'Was liegt am Strand und kann man nicht gut verstehen? Eine Nuschel.'),
(224,'Was machen PiratInnen, wenn Sie nicht mehr weiterwissen? Einen Arrrrrrrbeitskreis.'),
(225,'Was machen Tiere in der Disko? Sie diskotieren.'),
(226,'Was machen zwei Bäume, wenn sie einen trinken wollen? Sie gehen in ihre Stammkneipe.'),
(227,'Was machen zwei wütende Schafe? Sie bekommen sich in die Wolle.'),
(228,'Was macht Olaf in stressigen Situationen? Er bewahrt einen kühlen Kopf.'),
(229,'Was macht der Mathematiker beim Skifahren? Er rechnet mit Brüchen.'),
(230,'Was macht der Ostfriese wenn er zu Hause mehr elektrische Anschlussleistung braucht? Er geht mit dem Eimer raus und holt sich ein paar Kilo Watt.'),
(231,'Was macht die Security in der Nudelfabrik? Die Pasta auf.'),
(232,'Was macht ein Computer zur Entspannung? Er geht in den Ruhemodus.'),
(233,'Was macht ein Elektriker, der nicht weiß wo die Leitungen lang gehen? Er schaut in das Wo-Kabel-Heft.'),
(234,'Was macht ein Kettenraucher im Fitnessstudio? Glimmzüge'),
(235,'Was macht ein Metzger im Wald? Schnitzeljagd.'),
(236,'Was macht ein Steak unter dem Sofa? Sich versteaken.'),
(237,'Was macht ein arbeitsloser Schauspieler? Spielt keine Rolle.'),
(238,'Was macht eine Ente auf dem Router? Nat.'),
(239,'Was macht man damit Ecksen keinen Nachwuchs bekommen? Man Kastriert sie.'),
(240,'Was macht man mit einem Hund ohne Beine? Um die Häuser ziehen.'),
(241,'Was macht man mit einem angefahrenen Reh? Man rehanimiert es.'),
(242,'Was muss ein Computer machen wenn er sauer ist? Herunterfahren.'),
(243,'Was passiert in der Modeboutique? Das Schicksal.'),
(244,'Was passiert wenn man Cola und Bier gleichzeitig trinkt? — Man colabiert.'),
(245,'Was piekst und fliest das Bad? Ein Kachelschwein.'),
(246,'Was redet undeutlich und lebt im Wasser? Eine Nuschel.'),
(247,'Was sagt der Fuchs im Hühnerstall? Raus aus den Federn!'),
(248,'Was sagt der Holzwurmpapa abends zu seinen Kindern? Husch, husch ab ins Brettchen.'),
(249,'Was sagt der Teig bei der Hochzeit? Ich bin ganz gerührt!'),
(250,'Was sagt der frustrierte Origami-Lehrer zu seinem Schüler? Kannste knicken!'),
(251,'Was sagt der große Stift zum kleinen Stift? Wachs-mal-Stift.'),
(252,'Was sagt ein Ackerbesteller bei gutem Wetter? Das Land-wird.'),
(253,'Was sagt ein Gen, wenn es ein anderes trifft? - Halogen.'),
(254,'Was sagt ein Pirat im Pferdestall? A, Heu.'),
(255,'Was schwebt hölzern im All? Der Asttronaut.'),
(256,'Was schwimmt auf dem Teich und fängt mit Z an? Zwei Enten.'),
(257,'Was schwimmt im Meer und addiert? Ein Oktoplus.'),
(258,'Was schwimmt im Meer und multipliziert? Der Malhai.'),
(259,'Was sind die teuersten Tomaten? Die Geldautomaten.'),
(260,'Was sind kantige Tiere? Ecksen.'),
(261,'Was sitzt am Frühstückstisch und winkt? Ein Grüsli.'),
(262,'Was sitzt auf dem Baum und schreit "Aha!" - Ein Uhu mit Sprachfehler.'),
(263,'Was sitzt auf dem Turm und macht alle 15 Minuten Schuhu? Der Turmuhur.'),
(264,'Was sitzt auf einem Baum und winkt? — Ein Huhu!'),
(265,'Was sitzt ganz hinten im Brotkasten und ist beleidigt? Ein Schmollkornbrot.'),
(266,'Was sitzt im Baum und weint? Eine Heule!'),
(267,'Was steht Weihnachten im Wohnzimmer und ist kaputt? Ein Pannenbaum.'),
(268,'Was steht auf dem Herd und ist total geheim? Ein Topf Secret!'),
(269,'Was steht auf der Weide und ist müde? Ein Schlaf.'),
(270,'Was stinkt hier so? Die Kloketten.'),
(271,'Was studiert man für einen Führerschein? Fahr-ma-kologie.'),
(272,'Was trinken Koalas am liebsten? Das CocaKoala.'),
(273,'Was veranstalten Berge gegen den Klimawandel? Einen Krisengipfel.'),
(274,'Was will ein Astronaut? All-les.'),
(275,'Was wird nie teurer? Freibier.'),
(276,'Was wird oft übersehen? Ein Gartenzaun.'),
(277,'Welche Fische haben die beste Mundhygiene? Die Zahnprophylachse.'),
(278,'Welche Handwerker essen am meisten? Maurer, die verputzen ganze Häuser.'),
(279,'Welche Kuh klebt gerne an Wänden? Das Kuhgummi.'),
(280,'Welche Schuhe tragen Raubfische sehr gern? Hai-Heels.'),
(281,'Welche Tiere stehen voll auf Mode? Klamotten.'),
(282,'Welche Weinsorte wächst am Fuße des Vesuvs? Glühwein.'),
(283,'Welched Tier schreibt sich noch mit einem Buchstaben? Der V.'),
(284,'Welcher Buchstabe ist der coolste? Ohmega.'),
(285,'Welcher Bösewicht ist voll geladen? Voltemord.'),
(286,'Welcher Fisch nervt im Unterricht? Na der Stör!'),
(287,'Welcher Hund ist immer müde? Der Schläferhund.'),
(288,'Welcher Käse schimpft immer? Motzarella.'),
(289,'Welcher Vogel geht ständig auf die Toilette? Na der Klolibri!'),
(290,'Welcher Vogel sitzt immer auf dem Klo? Der Kakadu.'),
(291,'Welches Essen fördert Corona? Schnupfnudeln!'),
(292,'Welches Essen ist voll der Knaller? Dönermit.'),
(293,'Welches Essen schaut immer böse drein? Das Sauerkraut.'),
(294,'Welches Fortbewegungsmittel hat eine Pandaphobie? Der Bambus.'),
(295,'Welches Gemüse serviert sich selbst? Die Obergine.'),
(296,'Welches Getränk trinken Firmenchefs? Leitungswasser.'),
(297,'Welches Instrument ist aufgeweckt? Die Muntermonika.'),
(298,'Welches Instrument spielen Impfgegner? Querflöte.'),
(299,'Welches Küchengerät funktioniert nie richtig? Der Bugofen.'),
(300,'Welches Maultier sitzt in der Bar und trink Cappuccino? Das Cafémel.'),
(301,'Welches Nahrungsmittel hilft bei seelischem Kummer? Trostbrot.'),
(302,'Welches Obst geht immer in die Kirche? Die Frommbeere.'),
(303,'Welches Obst verarscht immer andere? Die Aprilkose.'),
(304,'Welches Tier badet gern in Tomaten, Basilikum und Olivenöl? Der Mozzarellensittich.'),
(305,'Welches Tier hält immer Maß? Der Ellensittich.'),
(306,'Welches Tier ist ein Genie in Mathe? Das Plusspferd.'),
(307,'Welches Tier kann nicht hören? Die Taube.'),
(308,'Welches Tier klebt gerne zwischen den Zähnen? Der Karamellensittich.'),
(309,'Welches Tier kümmert sich um Meeresbewohner, denen es nicht gut geht? Die Krakenschwester.'),
(310,'Welches Tier schreibt sich mit einem Buchstaben? Die Q.'),
(311,'Welches Tier trägt Strapse und Korsett und ist auch sonst eher verrucht? Der Bordellensittich.'),
(312,'Welches ist das beliebteste Lied zu Weihnachten bei den Dinos? Ihr Kinderlein Komet.'),
(313,'Welches ist der faulste Dinosaurier, der nur rumliegt? Der Brach-iosaurus.'),
(314,'Wenn Dinos eine Brille brauchten, dann gingen sie zum alten Archäopterix.'),
(315,'Wenn eine Kapselkaffeemaschine das Zeitliche segnet, schlägt die Stunde des Senseomanns.'),
(316,'Wer hat Darth Vader auf den Kopf gekackt? Der Star wars.'),
(317,'Wer ist bunt, flattert durch die Luft und hilft wo er nur kann? Ein Retterling.'),
(318,'Wer ist der fröhlichste Held? Happy Potter.'),
(319,'Wer ist der lustigste Bösewicht? Loldemort.'),
(320,'Wer ist grün, kann zaubern und riecht streng? Stinkerbell.'),
(321,'Wer kommt in Hogwarts immer zu spät? Harry Flotter'),
(322,'Wer kümmert sich um die Gräten der Meeresbewohner? Der Oktopäde.'),
(323,'Wer mit Nüssen zahlt, darf sich nicht wundern, wenn Affen für ihn arbeiten.'),
(324,'Wer war der erste DJ? Der Triceratops. Der hat beim Schlafen immer seine Rückenpanzerplatten aufgelegt.'),
(325,'Wer war der größte Dinosportler der Welt? Der Pterodartylus.'),
(326,'Wer wohnt im Dschungel und schummelt? Mogli.'),
(327,'Wie begrüßen sich Schönheitschirurgen? Na, was machst Du denn für ein Gesicht?'),
(328,'Wie berechnet eine Kuh die Fläche ihrer Weide? Mit der Muhtiplikation.'),
(329,'Wie heißt das intelligenteste Gemüse? - Schlaubergine.'),
(330,'Wie heißt der Bruder von Elvis? Zwölfis.'),
(331,'Wie heißt der Erfinder der Shorts? Kurt C. Hose.'),
(332,'Wie heißt der Hengst? Pferdinand.'),
(333,'Wie heißt der Lieblingskäse eines Sportlers? Schwitzer Käse.'),
(334,'Wie heißt der Tiger mit Vornamen? - Schaumfes!'),
(335,'Wie heißt der nordische Gott der gewaltfreien Konfliktlösung? Der Mediathor.'),
(336,'Wie heißt der stinkende Keks? Poreo.'),
(337,'Wie heißt die musikalischste Leckerei? Popcorn.'),
(338,'Wie heißt die verseuchteste Stadt? Budapest.'),
(339,'Wie heißt ein Keks an der Börse? Spekulatius.'),
(340,'Wie heißt ein asthmatischer Saurier? Bronchiosaurus.'),
(341,'Wie heißt ein kommunistischer Tyrannosarurus Rex? Stalinosaurus.'),
(342,'Wie heißt eine kleine, 4-saitige Gitarre aus fair gehandeltem Holz? Ökolele'),
(343,'Wie hieß die bekannteste Klempnerfirma der Dinos? Diplolocus.'),
(344,'Wie hieß die beliebteste Kochplatte der Dinos? Tri-Ceran-Tops.'),
(345,'Wie ist die Handschrift eines Tintenfisches? Krakelig.'),
(346,'Wie kann man entspannt Geld anhäufen? Mit einem Spa-Schwein.'),
(347,'Wie kastriert man einen Kühlschrank? Tür auf, Eier raus, Tür zu.'),
(348,'Wie nennt man Han Solo, wenn er in der Disko rumtanzt? Han Twerker.'),
(349,'Wie nennt man Kaninchen im Fitnessstudio? Pumpernickel.'),
(350,'Wie nennt man befreundete Gummibärchen? Haribros.'),
(351,'Wie nennt man das Küchengerät dass dir heimlich die Süßigkeiten wegisst? Die Spülnaschine.'),
(352,'Wie nennt man das Oberteil von Meerjungfrauen? Algebra.'),
(353,'Wie nennt man den Assistenten eines Schönheitschirurgen? Liftboy!'),
(354,'Wie nennt man den Flur eines Iglus? Eisdiele!'),
(355,'Wie nennt man den germanischen Gott der Ungeduld? Hammersbald.'),
(356,'Wie nennt man die Steigerung von Buchstabensuppe? Wörtersee.'),
(357,'Wie nennt man die Zeitform wenn der Bus pünktlich war? Buskamperfekt!'),
(358,'Wie nennt man ein Monster mit Schnupfen? Rotzilla.'),
(359,'Wie nennt man ein Rudel aggressiver Wölfe? Wolfgang.'),
(360,'Wie nennt man ein tiefgefrorenes Mammut? Hart-mut!'),
(361,'Wie nennt man ein verschwundenes Rindvieh? Oxford.'),
(362,'Wie nennt man ein weißes Mammut? Hell-mut!'),
(363,'Wie nennt man eine Ansammlung singender Wale? Orcapella Gruppe.'),
(364,'Wie nennt man eine Biene, die diagonal fliegt? Eine Quersumme.'),
(365,'Wie nennt man eine Frucht, die ein großes Anwesen hat? Eine Hektarine.'),
(366,'Wie nennt man einen Bumerang, der nicht zurück kommt? Stock.'),
(367,'Wie nennt man einen Bär der KungFu beherscht? Grizzly.'),
(368,'Wie nennt man einen Bären der "Granufink" braucht? Ein Pullerbär.'),
(369,'Wie nennt man einen Delfin mit einer Unterhose auf dem Kopf? Slipper.'),
(370,'Wie nennt man einen Deutschen im Weltraum? Allmann.'),
(371,'Wie nennt man einen Gerd, der den Rasen mäht? Gerd-ner.'),
(372,'Wie nennt man einen Hering, der Regie führt? Einen (Uwe) Bollmops.'),
(373,'Wie nennt man einen Hering, der am Flughafen arbeitet? Einen Zollmops.'),
(374,'Wie nennt man einen Hering, der beleidigt ist? Einen Schmollmops.'),
(375,'Wie nennt man einen Hering, der die besten Memes postet? Einen Lolmops.'),
(376,'Wie nennt man einen Hering, der doofe Kommentare schreibt? Einen Trollmops.'),
(377,'Wie nennt man einen Hering, der gerne Atombombentests macht? Einen Atollmops.'),
(378,'Wie nennt man einen Hering, der gerne Befehle befolgt? Einen Jawollmops.'),
(379,'Wie nennt man einen Hering, der gerne strickt? Einen Wollmops.'),
(380,'Wie nennt man einen Hering, der immer alles aufschreibt? Einen Protokollmops.'),
(381,'Wie nennt man einen Hering, der immer alles machen muss? Einen Sollmops.'),
(382,'Wie nennt man einen Hering, der immer nur traurige Musik spielt? Einen Mollmops.'),
(383,'Wie nennt man einen Hering, der immer sauer ist? Einen Grollmops.'),
(384,'Wie nennt man einen Hering, der immer total begeistert ist? Einen Tollmops.'),
(385,'Wie nennt man einen Hering, der sehr unkultiviert ist? Einen Prollmops.'),
(386,'Wie nennt man einen Hering, der sich für Umfragen interessiert? Einen Pollmops.'),
(387,'Wie nennt man einen Hering, der total besoffen ist? Einen Vollmops.'),
(388,'Wie nennt man einen Hering, der total gerne Puppen mag? Einen Dollmops.'),
(389,'Wie nennt man einen Hund der gerne Äpfel isst? Apfelpudel.'),
(390,'Wie nennt man einen Landwirt mit Studium? Einen Ackerdemiker.'),
(391,'Wie nennt man einen ausgehungerten Frosch? Magerquark.'),
(392,'Wie nennt man einen dicken Schriftsteller? Kugelschreiber!'),
(393,'Wie nennt man einen dünnen Weihnachtsmann? Nikolauch.'),
(394,'Wie nennt man einen extrem dünnen Frosch? Magerquak.'),
(395,'Wie nennt man einen hungrigen risikobereiten Wellensittich? Trill-Seeker'),
(396,'Wie nennt man einen kleinen Matrosen, der sich nicht wäscht? Na: Ein Meerschweinchen!'),
(397,'Wie nennt man einen kleinen Türsteher? Sicherheitshalber.'),
(398,'Wie nennt man einen schlechtgelaunten T-Rex? Dinosaurier'),
(399,'Wie nennt man einen unfreundlichen Milliardär? Eurogant.'),
(400,'Wie nennt man einen veganen Vampir? Graf Rucola!'),
(401,'Wie nennt man einen überfahrenen Vogel? Piepmatsch!'),
(402,'Wie nennt man es, wenn man nicht mehr aufhören kann, frittierte Kartoffeln zu essen? Krokettenreaktion'),
(403,'Wie nennt man heute einen Hofnarr? Untertainer.'),
(404,'Wie nennt man jemand der nur so tut als würde er etwas werfen? Einen Scheinwerfer.'),
(405,'Wie sieht das Kind des Metzgers aus? Wie aus dem Gesicht geschnitten.'),
(406,'Wie sperrt man das Spielzimmer ab? Mit einem Kinderriegel.'),
(407,'Wie viel wiegen ein Pferd und ein Hund zusammen? Ein PfHund!'),
(408,'Wie viele Psychotherapeuten braucht man um eine Glühbirne zu wechseln? Einen, aber die Birne muss auch wollen.'),
(409,'Wie viele Softwareentwickler braucht man um eine Glühbirne zu wechseln? Keinen, das ist eindeutig ein Hardwareproblem.'),
(410,'Wieso bleibt das Pferd ständig stehen? Vermutlich ein Problem mit der Hüdraulik.'),
(411,'Wieso können Seeräuber keinen Kreis fahren? - Weil sie Pi raten.'),
(412,'Wieso werden auf diesem Bauernhof Medikamente verkauft? Das ist eine Ratiopharm.'),
(413,'Wieviele Dinos braucht man, um eine Glühbirne einzustecken? Nur einen, den Glühbirnosaurus Stecks.'),
(414,'Will jemand einen Witz über Natriumhydrat hören - NaH!'),
(415,'Wo baden Eisbären am liebsten? Im Nordpool.'),
(416,'Wo geht Darth Vader shoppen? In der Darth Mall!'),
(417,'Wo geht ein Vampir essen? Zum Imbiss.'),
(418,'Wo gibt es die meisten Gespenster in Europa? In Buuuuuuuuhdapest!'),
(419,'Wo ist die Deutschlandzentrale von Burger King? In Whoppertal.'),
(420,'Wo kommt das Essen rein? Dortmund.'),
(421,'Wo leben Mobber zusammen? In einer Gemeinschaft.'),
(422,'Wo lernen die Ferkel? In der Grunzschule.'),
(423,'Wo machen Kühe Urlaub? Auf Kuuuhba!'),
(424,'Wo machen Schweine Wellness? In der Sauna.'),
(425,'Wo parkt ein Admin seine Yacht? Im Bootsektor.'),
(426,'Wo verlieben sich Computer? Bei einem UpDate.'),
(427,'Wo wohnen Katzen? Im Mietz-Haus!'),
(428,'Wo wohnt der Hamster? In Hamsterdamm.'),
(429,'Wo zeltet man besonders schön? In Campten.'),
(430,'Woher bekommt Pampel seine Ideen? Von seiner Muse.'),
(431,'Wohin gehen Arzt und Ärztin zum feiern? Auf den Medizinball.'),
(432,'Wohin geht ein Baum, wenn er Rückenschmerzen hat? Zum Kiefer-Orthopäden.'),
(433,'Wohin geht ein Zyklop, wenn er nicht gut sieht? Zum Augearzt.'),
(434,'Wollte Socken bei H&M kaufen. Oma strickt dagegen.'),
(435,'Womit attackieren Piraten mit Verdauungsproblemen? Mit Schisspulver, Kackanone und Pisstolen.'),
(436,'Womit backen Schlümpfe? Mit Garga-Mehl.'),
(437,'Womit ist der Boden eines Iglus ausgelegt? Mit Eisdielen.'),
(438,'Womit kann man eine Webseite hosten, aber nur wenn Vollmond ist? Mit einem Werserver.'),
(439,'Womit messen Bäcker die Größe von Croissants? Mit einem Eichhörnchen.'),
(440,'Womit verprügeln sich Schafe? Mit dem Mäh-Drescher.'),
(441,'Womit verzieren Rinder ihren Kuchen? Mit Kuhvertüre.'),
(442,'Worin entführt der Pirat seine Geliebte? In der Schatztruhe.'),
(443,'Wovon träumt eine Katze nachts? Von einem Muskelkater.'),
(444,'Wussten Sie, dass Esoteriker häufig zur Arbeit pendeln...?'),
(445,'Zu welchem Arzt geht Pinocchio? Zum Holz-Nasen-Ohren-Arzt.'),
(446,'Zu welchem Fest wird am meisten getrunken? Weinnachten');
